* generate_cz_shapefile.do: Merges 1990 County shapefile into a 1990 CZ shapefile

*** Version history:
* 2013-07-14, Michael Stepner
* 2013-07-05, Michael Stepner* 2013-04-15, Shelby Lin/*******************************

** INPUT FILES ** 
- cw_cty_czone.dta
	Provided by David Dorn at http://www.cemfi.es/~dorn/data.htm -- file [E6]
- county1990_database_clean.dta & county1990_coords_clean.dta
	Based on source file "co99_d90_shp.zip", provided by U.S. Census Bureau at http://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html
	Generated by "import_county1990_shapefile.do"
** OUTPUT FILES **- cz_database_clean.dta- cz_coords_clean.dta*******************************/
*global dropboxroot "/Users/michael/Dropbox"
*global dropboxroot "C:/Users/RA 2/Dropbox"*global root "$dropboxroot/ra_working_folder/shapefile_generation"
global root "/Users/michael/Documents/Harvard RA/41 - shapefile_generation"

global raw "$root/raw_data"set more off

*** Step 1: Use Dorn County -> CZ crosswalk to merge CZ variable onto county database
use "$raw/cw_cty_czone.dta", clear
rename cty_fips county
rename czone cz
keep county cz

merge 1:m county using "$root/map_shapefiles/county1990_database_clean", assert(3) nogen
compress

save "$root/map_shapefiles/cz_database_temp.dta", replace



*** Step 2: Merge county polygons into CZs

mergepoly id using "$root/map_shapefiles/county1990_coords_clean", ///
	coordinates("$root/map_shapefiles/cz_coords_clean.dta") ///
	by(cz) replace
save "$root/map_shapefiles/cz_database_clean.dta", replace


*** Step 3: Erase temp file

erase "$root/map_shapefiles/cz_database_temp.dta"
